### ISSUE TITLE
Is there a similar plugin available for CESIUMjs

### ISSUE THREAD

**Issue by ankit-shibu** [danwild/wind-js-leaflet#10]

**Comment by danwild** [comment]
I don't know if there is something already out there - but you should be able to port this functionality to CesiumJS fairly easily. 

I'd start by looking at other example of using `canvas` layers in cesium (e.g. [cesium-heatmap ?](https://github.com/danwild/CesiumHeatmap))

**Comment by ankit-shibu** [comment]
Thanks!!!
