### ISSUE TITLE
Windspeed varies on zoomlevel

### ISSUE THREAD

**Issue by Grandmasg** [danwild/wind-js-leaflet#2]
Spotted something strange or an bug??
Zoomed out:
![zoomed out](https://cloud.githubusercontent.com/assets/6714237/20642075/588daae0-b406-11e6-9b80-462f752eb301.png)
Zoomed in:
![zoomed in](https://cloud.githubusercontent.com/assets/6714237/20642076/5a3ea056-b406-11e6-878e-46b4ee571dfe.png)

**Comment by danwild** [comment]
Thanks @Grandmasg, fixed in 5ef8c8414e4805a1538e6e82d422b608c21ae15b
