### ISSUE TITLE
How to load real-time wind data from server?

### ISSUE THREAD

**Issue by IsaacHub** [danwild/wind-js-leaflet#5]
@danwild 
I have set localMode to false, but how to retrieve new real-time info from server??

Right now the wind data is coming from the demo.json, but how to use real wind data??

What to replace these three URLs with?? 
pingUrl: 'http://localhost:7000/alive',
latestUrl: 'http://localhost:7000/latest',
nearestUrl: 'http://localhost:7000/nearest',

WindJSLeaflet.init({
	localMode: false,
});
How to download the latest new JSON file automatically??

**Comment by claytongroth** [comment]
I am also wondering the same thing. 

Thanks!

**Comment by danwild** [comment]
You need to run your own server, one that returns JSON data in expected format - and replace the three URLs above with your own.

As noted in the [README](https://github.com/danwild/wind-js-leaflet#wind-js-leaflet-), [wind-js-server](https://github.com/danwild/wind-js-server) provides one example of how to do this.

Also note that this project has been superseded by [leaflet-velocity](https://github.com/danwild/leaflet-velocity)
