### ISSUE TITLE
wind-js addto map on load

### ISSUE THREAD

**Issue by Grandmasg** [danwild/wind-js-leaflet#7]
@danwild

I'm trying to get the wind-js overlay to be active on page load... only i cannot find the solution.
I tried to add it with .addTo(map); at various locations/functions and failed :(

How do i load the wind-js on page load?

**Comment by danwild** [comment]
This project has been superseded by [leaflet-velocity](https://github.com/danwild/leaflet-velocity), which among other things - provides more robust control of the animation layer.
